# Introduction {#intro}

Patterns of political beliefs are not random. People who hold certain ideas often hold others. An individual on the "political left" is likely to hold views clustering in certain specific ways with regards to, for instance, economic redistribution, immigration policy, environment policy, or human rights. Similarly, an individual on the "political right" will hold relatively coherent beliefs, and often different, to those held by a leftist. Of course, the political space is not perfectly unidimensional or bi-dimensional, or x-dimensional. Researchers and analysts often disagree about the number of dimensions, or the best ways to label them. At minimum, they usually agree it depends on context. For instance, introductory textbooks talk of a unidimensional left-right spectrum, or a bi-dimensional (Authority/Liberty--Left/Right) spectrum [@heywood2017political]. @heroux2016substate uses statistical modeling to identify five dimensions in the Canadian context. Neither do such clusters or dimensions possess universal or time-invariant validity. In the Canadian province of Québec, it is widely recognized that there has been a realignment, from a dominant federalism/sovereignty dimension to a more traditional left-right dimension [@montigny2016fin].  Nonetheless, there is a consensus that "left" and "right" are meaningful concepts when talking about politics, and that spatial representations of politics do help us make sense of the political landscape. One can make sense of ideology through some form of "empirical reduction".

Similarly, one can make sense of "identity" through similar techniques. Without a doubt, political identities are plural and wavering [@hobsbawm2012invention,@ozkirimli2017theories]. Still they can be fruitfully studied to extract a core; to tell something about the identity's root [@schwartz1967public]. As the researcher can place the subject amid a spatial ideological representation, one can associate empirical symbols to cluster of political identities [@dufresne2019symbolic].     

One important way, and in a sense the only way, to study political beliefs (about ideology or identity) is through language; through what people say orally and in writing. All human communication requires language, words, and meanings. This is apparent in all approaches to the study of politics. It is most obvious in political theory, where commentators reflect at lengths over questions of politics, justice, or institutions, and in qualitative research, where analysts examine the deep structure of some data, usually linguistic in nature. Yet, in the social sciences, language also features centrally in quantitative work; most survey statistics uses linguistic data (questions, survey choices), ideal points models estimate ideology from roll-call data, i.e., data representing whether a politician agrees with specific policies or bills.

Traditionally, scholars have studied patterns of political beliefs (political ideology or political identity) either through quantitative approaches (surveys, scaling, scores of various natures, etc.) or through theoretical approaches (political theory, interpretative approaches, critical approaches, etc.) Of course, it has been common to combine these approaches; to combine thicker and thinner descriptions, as befits the object of study.

Automatic content analysis methods have long promised to try to bridge the gap between quantitative and qualitative-theoretical perspectives. It has been difficult: extracting meaning from text is hard.  It is not for lack of effort: political scientists have laboured intensively on text scaling methods. Approaches based on word frequencies in text [@slapin2008scaling,@laver2003extracting] allow to compare policy positions. Supervised classification of political texts into known categories help us study tone, partisan affiliation, or any pre-determined categories which an algorithm can learn and then put texts into. These methods have allowed us to make important advances. Nevertheless, they remain at a high level of abstraction. The unit of analysis is the document in the case of text scaling; classification is useful but does not really get at the sense or the meaning in the text.

Word embeddings have recently emerged as a promising way to get at meaning. Word embeddings stem from statistical semantics and can be summarize by the distributional hypothesis: words used and occurring in similar contexts tend to have similar meanings. It is then possible to model and represent in high dimensional space each word (or each political concepts if they are represented by one or several words). Technical advances (the idea behind word embeddings has been around for decades but efficient and mainstream implementation is recent [@mikolov2013distributed,@mikolov2013efficient] have the potential to offer new perspectives to the study of political meaning. Some researchers have started using such methods, but, in the social sciences, their use is still in its infancy. My dissertation uses statistical semantics to study ideology and political identity in Canada. Using textual data from transcripts of Parliamentary Debates (1900-2019) and Twitter data, I study patterns of word use, over time and context (e.g. elites vs non-elites, left vs right). I aim to get at word and concept meaning, using word vectors, in the context of discussions about Canadian politics.  
