# Literature review

## From quantitative large-N surveys to word embeddings

People holding certain political beliefs often hold others. In this dissertation, I call ideological analysis the general study of those political beliefs. Ideological analysis, in this context, includes the study of what empirical political science usually calls ideology (latent policy dimension), but also symbols and markers of political identity. Ideology, thus understood, is a loaded term; it can mean very different things. These meanings range from the French ideologues's "objective" study of ideas just before and during the French revolution [@kennedy1979ideology;@head1985ideology] to illusion, mystification or false consciousness in Marx and Engels' German Ideology [-@marx1970german], or a morphological, conceptual, non-pejorative map of the sociopolitical world [@freeden2003ideology], and include various spatial scaling methods; measuring what is called the left and right, conservative and liberal positions; in one, or multiple dimensions; measurable in real life [@downs1957economic;@aldrich1977method;@hare2015using;@cochrane2015left] or online [@barbera2015birds;@temporao2018ideological]. Understanding precisely the patterns that hold these ideas together is a matter of considerable debate. @maynard2013map divides in three broad groups these motley vantage points: conceptual approaches, discursive approaches and quantitative approaches.

Conceptual approaches focus on systems of ideas: concepts and their complex interrelations function as the unit of analysis. Ideologies provide frameworks from which individuals understand the world. Freeden's [-@freeden2006ideology] morphological approach is an influential example. Foundational principles such as "liberty", "security" or "equality" are shared by the great vast majority, yet adherents of different ideologies understand those principles in a different and sometimes conflicting way. Political concepts acquire meaning through discourse, culture and positionality. Ideologies evolve through conceptual competition; through "decontestation". Other scholars working in this tradition include Reinhart Koselleck (conceptual history), and Quentin Skinner (Cambridge School of historicist and contextualist interpretation). Some have formalized this analysis of the structures that underlie social interactions, via, for instance, complex systems [@thagard2012mapping;@homer2014conceptual].

Discursive approaches focus on communicative practices. They are less concerned with content, and more concerned with visibility, power, and influence. Crucially, they usually involve a critique of ideology from the left. While epistemological disagreement exists on matters of relations to truth, with post-structural discursive approaches [@mouffe1985hegemony;@zivzek1989sublime] more sceptical than critical discourse approaches [@van2006ideology;@fairclough1992discourse], both strands share a commitment to the critique of naïve conceptions of truth [@kellner1989critical]. Vast methodological differences also cleave the field, from the study of semantics [@pecheux1975language], to the post-Marxist attention paid allegory [@jameson2020allegory], speed [@baudrillard1994simulacra] , spectacle [@debord2012society], or empty signifiers [@laclau2007emancipation]. Through the study of linguistics or discursive constructions, critical approaches hence shed light on the origins of, and the process by which, ideas, which may or may not be, but usually are, problematic and alienating, come to reproduce themselves to the point of insidious symbolic hegemony. Recently, discursive analysis has been extended to include statistical based approaches [@nafstad2012ideology] relying largely on word count. In the context of ideological analysis, frequency usage of communality words (solidarity, welfare) or words linked to consumerism can provide insight in possible changes in the way individuals construe and reproduce political behaviours [@nafstad2012ideology]. 

Quantitative approaches use large-N analyses to study patterns of beliefs. A divide exists between observational studies of ideology studying citizens’ stated preferences [@bonica2013ideology] or legislators’ voting behaviour [@martin2002dynamic], and approaches in social psychology, rather focusing on cognitive biases, links between belief systems and personality; ideology as social cognition, for instance by linking political preferences to psychological inclinations toward uncertainty or threat [@jost2013political]. Quantitative approaches also include traditional dimensionality reduction, where values are reduced to dimensions: see @heroux2016substate for an investigation of the Canadian case; @cochrane2010left for a study of ideological asymmetries.

As such, ideological analysis is fragmented. For instance, experimental social psychology can look down on non-experimental approaches, where falsification is less straightforward. Conversely, non-quantitative scholars can look down upon the poor external validity of experiments, or their theoretical levity. Calls have been made to see, use and combine the full variety of available approaches. Especially, to see ideological analysis as "a field in its own right": researchers from various strands have common core objectives, how people talk about politics, and how it is significant [@maynard2013map].

My dissertation proposes such a combination of frameworks to study ideology. Substantively, I aim to map the changing meaning of political words over ideology, time and ideology/time interactively. Methodologically, I will call upon recent advances in the computer science field of natural language processing. Namely, the dissertation’s methodological workhorse will be word embeddings: a set of techniques where words, phrases or documents are mapped to vectors of numbers. Conceptually, word embeddings organize words, phrases or documents in high dimensional space, where similar items are close to each other and dissimilar items are not. Perhaps, ‘immigrant’ will be close to ‘refugee’ but not to ‘parliament’; ‘parliament’ will be close to ‘institution’, but not to ‘climate change’. Embeddings are calculated based on distributions of words in large corpora, and their proximity to other words. In other words, in linguist J.R. Firth’s [-@firth1957papers] now celebrated terms: "You shall know a word by the company it keeps".

Most work in the quantitative social sciences has studied ideology from the point of view of dimensionality reduction and regression. Dimensionality reduction is ambiguous in what it reveals. Dimensionality reduction tells us if there is a fit between political beliefs [@gregg1965dimensions], but not how it forms or where it’s from. Regression analysis finds bivariate or multivariate links. For instance, in average, education is related to views on abortion. Neither approaches are perfect as they often fail to explain family resemblance-like phenomena. Left-right positioning is one such phenomena [@cochrane2015left]. It arises when it’s not that members of a family have significantly bigger noses, or lighter-eyes, or darker hair than the rest of the population. Rather, it’s when some combination of those characteristics makes it likely to hold others. In politics, such combinations are frequent. Studying the emergence of fringe communities and political echo chambers using closeness centrality in a network can reveal multiple communities and their interactions in a way impossible to traditional statistical methods [@boutyline2017social]. Ideological scaling and spatial models of politics using traditional statistical methods or network approaches then allow to address one of the most salient questions for academics and citizens alike: to what extent is society ideologically polarized, and is there increasing polarization?

Work on ideology and spatial representation has mostly used likert-type items. Dimensionality reduction is often used on categorical, ordinal or numerical variables. This way of working limits possible nuance for the respondent but simplifies the researcher's task. Working on a set of questions with answers varying only over a certain range or a certain support entails postulating that the ideological world can be conceptualized as such. Yet, making this chief assumption allows for useful and enlightening insight on the structure of politics (for a classic example see @aldrich1977method). It certainly would involve some work, but it appears reasonable to believe that replacing close-ended question by longer open-text when studying political ideology, would allow to extract more substance, and increase the precision of our ideological model [@bauer2017left].

Recent work has focused on exactly this: fitting models predicting the use of words in context to generate estimates of ideological placement [@rheault2020word;@rodman2020timely]. Thus, I propose to extend such work. These models often use word embeddings [@rumelhart1986learning;@mikolov2013efficient;@mikolov2013distributed].  Each word is mapped to a large numerical vector. The given vector represents the context in which the word is generally used. The method depart significantly from bag-of-words methods traditionally used in political science where word count is the main predictor of various outcome measures. @rheault2020word have argued that taking into account the role of words in context is especially promising for scholars attempting to measure political ideology. Patterns of ideas often are tangible, but irreducible as ideology functions in a network-like way: ideas are loosely associated, clusters or patterns emerge, people know ideology when they see it, yet struggle to name things as they are. Ideology functions in a plastic way. [@cochrane2015left] Word embeddings, since words are at the center of the network of words with which they are used, are designed to capture such interplay.

Usually, researcher study only one single type of texts. @rheault2020word study parliamentary texts. @rodman2020timely analyses newspaper articles from the New York Times, Reuters and Associated Press. @rodriguez2021word model words in congressional speeches. This dissertation aims to model word use and ideology from various sources: citizens, journalists, and parliamentary text. Political ideology does not arise from debates in parliament only. Similarly, pundits or political theorists do not have the monopoly over the way language is used to express political belief. Ideology emerges not within one social group or institution, but through social practices shared by citizens, politicians, pundits, theorists alike. There will be some differences, but a language-based theory of ideology must be applicable to more than one case. The study of ideology should be pluralistic in its objects: various actors, from all over society, produce ideological speech, in turn influencing the speech of various actors. 

One common difficulty arising from the modelling of ideology through text motivates this research. Often, such modelling identifies other dimensions, clearly non-ideological [@hirst2010party;@lauderdale2016measuring]. Instead of capturing ideology, statistical models use words to learn "something else", like expressions of attack and defence, opposition and government, geographical differences, linguistic complexity, and so forth. Such findings emerge mostly from studies using word-count-like features, not word embeddings. Rheault and Cochrane’s findings suggest embeddings might be a solution to this problem of ideological identifiability. The dissertation aims to test this solution on text non-parliamentary texts, and in more than one language. 

One further difficulty concerns the measure of uncertainty. Producing estimates without measuring uncertainty can be misleading. Estimates without a measure of uncertainty can suggest a precise result that should actually be interpreted quite differently if a large uncertainty measure was reported. @han2018conditional propose a variational Bayesian approach for estimating parameter uncertainty. Several approaches to get at uncertainty can be tested. A first is to leverage the fact that embeddings are usually underdetermined. This means that running the same model twice gives different results. The numerical estimates will not be the same. However, if the model is successful, the relative results will be the same, i.e. word will have the same "meaning" as measure through distance. Hence, one might be able to measure uncertainty through some form of bootstrapping The second method would be similar, also using bootstrapping but with replacement, changing the text slightly each time; but replacing words with similar words. Estimates with uncertainty will be measured against "objective measure of ideology". In the case of citizens, this can take the form of vote choice, or self-placement on a numerical axis. For pundits or politicians, it can be more complicated to find an objective measure. Comparing estimates and their uncertainty to expert judgments, the idea is to produce estimates that generally make sense. For example, measuring the ideology of politicians in the Canadian parliament, members of the New Democrat Party should be to the left, members of the Liberal Party of Canada in the center, and members of the conservative party on the right, uncertainty should overlap between and within parties.

## Distributional semantics

The previous subsection has introduced the idea of word embeddings: high dimensional vectors encoding the meaning of a word such that similar words have similar positions; are close to one another. In that section, word embeddings have been presented as one interesting way to produce some empirical ideological analysis; as the latest in a series of quantitative methods to study political behaviours and ideas. The present section shifts the focus on the linguistic properties and foundations of word embeddings: word embeddings as part of the research area called distributional semantics, or distributional approaches generally. Many of the ideas explored are largely inspired by @sahlgren2008distributional. 

Sahlgren suggests distributional approaches rely on a set of assumption referred as the "distributional hypothesis". This hypothesis can be stated in various forms: 

"words which are similar in meaning occur in similar contexts" [@rubenstein1965contextual]; "words with similar meaning will occur with similar neighbors if enough text material is available" [@schutze1995information]; "a representation that captures much of how words are used in natural context will capture much of what we mean by meaning" [@landauer1997solution]; and "words that occur in the same contexts tend to have similar meanings" [@pantel2005inducing].

Sahlgren summarises: the distributional hypothesis is about "a correlation between distributional similarity and meaning similarity which allows us to utilize the former in order to estimate the latter". 

To examine this "distributional hypothesis assumption", two questions can be asked. The first question is about the kind of distributional properties we are looking for (and in practice a question about algorithms). The second question asks "in what sense it is meaning that is conveyed by distributional patterns" [@sahlgren2008distributional]. The first question, about the choice of algorithm, will be covered in the next section on methodology. What it means to get at meaning through word embeddings is explored in this section. This will be expanded in the dissertation. 

The key idea discussed  will be the common critique raised against distributional semantics and word embeddings: that they do not get at meaning because they only study the text, and not the world. Sahlgren's narrative is about the structuralist foundations of distributional approaches. Theories of meaning often ask if meaning is to be found in the mind (e.g. idealism), in the world (e.g. materialism, physicalism) or in the text (e.g. structuralism word embeddings). A model of meaning can situate it in anyone of mind, world or text, but situating it in the text has the pragmatic advantage of predictive power and of current large scale use. Work in political science usually mentions Firth and the distributional hypothesis [@rheault2020word;@rodman2020timely;@rodriguez2021word;@rodriguez2021embedding] but, usually stops at Firth. The point of this grounding in structuralism is that it makes explicit what can be shown with word embeddings and what cannot (i.e. word embeddings are not very useful from the perspective of a Correspondence Theory of Truth or a Verificationist Theory of Truth, but useful from the perspective of a Pragmatist or Coherentist theory of Truth; they make sense if you accept meaning holism and they don't if you swear by atomism about meaning). It is not necessarily evident why such a discussion belongs in political science, rather than in philosophy, but I think it is useful to reply to one frequent objection to text-as-data methods: that they don't work in practice. I think that sometimes they work well and sometimes they don't, but that mostly they are useful. In particular, I think that discussing some arguments in favor and against meaning holism can help alleviate problems associated with the intuition that words should have one-to-one relations with objects outside of the text.

## Ideology and identity in Canada: changing meanings

This theoretical and methodological setup is necessary although secondary to the main objective: describing and measuring the changing meanings of key concepts used to talk about Canadian politics. Canada has a different history than those countries we usually think of as most similar, namely the United States and countries in Western Europe. Living next to the U.S. is like “sleeping with an elephant” said Pierre Trudeau, at the same time its European origins remain evident [@resnick2020european]. Canada's identity has always been ambivalent, is it mono-national or pluri-national, does it have a culture, a "biculture", or "multicultures"; what about aboriginal cultures? [@wiseman2011search] And, of course, is this changing, and how, over time? To cite a recent paper, describing this ambivalence [@dufresne2019symbolic]: 

> "In a nutshell, Canada is an immigrant nation founded, quite recently, on native land over an enormous territory by two linguistically distinct colonial groups – the English and French. If we add to this a hegemonic threat from a powerful American neighbour, a Quebec separatist movement, strong regional resentment in the West, and Aboriginal claims, Canada’s difficulty in finding shared symbols to define the nation seems unsurprising."

Studying Canadian ideology and identity, we will focus on what it means to be Canadian. The question will be addressed both from the angle of identity (what it means culturally, origins, symbols) and ideology (does citizenship “involves” redistribution, openness to immigrants, justice, etc.). We identify four key concepts: citizenship, identity, nation and rights. A more extensive literature review will be included in the dissertation. For now, we can say that Canadian identity and nationhood was intrinsically linked to a “British connection” for close to 100 years following Canada’s founding in 1867. This “British connection” of course was not part of the identity of those identifying as French Canadians. Starting in the 1960s, following similar developments in other Western countries, a diversification of identity claims began. In many ways, being Canadian was not necessarily about being French, English/British or Indigenous, but from a more plural and heterogeneous experience, some would say a post-national experience. Around the same time, Canada experienced a constitutional maturation with a Rights Revolution. Between 1931’s Statute of Westminster, when Canada achieved independence from Britain and 1982’s patriation when Canada obtained full sovereignty over it’s constitution, there was the emergence of a “rights mentality”: individual rights were becoming less abstract, and more something that Canadians could rely on in their day to day lives. 

Where were politicians in the House of Commons standing on these developments? Empirically, around what period can we start to see a decline of “Britishness talks”? Similarly, can we observe the rise of “rights talk”? These questions are explored in the chapter on semantic change in the House of Commons.

