# Politicians and Twitter users talking about Canadian politics: how are they similar; how are they different?

This chapters focuses on semantic differences in the way politicians and users talk on twitter. The previous chapter using texts from the Hansard dataset used diachronic embeddings to study semantic change. The current chapter focuses on synchronic measures to capture differences in the way elites (politicians) and non-elites (users) express themselves. 

The chapter asks two research questions. First, when looking at word-use, are there significant differences in the ways political keywords such as “nation”, “citizenship”, “rights” and “identity” are used by elites and non-elites. Using methods such as à la Carte on Text, can we make statistical statements about how these word’s use varies. Second, the chapter will try to use this preliminary work to build a model of partisan associations. After having looked at the different meanings elites and non-elites assign to political keywords, can we use those to get at partisanship or ideology. More concretely, does the use of word vectors, representing meaning, increase the accuracy of a model of partisan affiliation or ideology, when compared to alternatives using bag of words approaches or approaches based on followers. 

Following @wu2019partisan, the idea is to learn associations between known partisan words and non-partisan words. These authors obtain partisan subspaces using analogy property of embeddings: a gender dimension, for instance can be calculated by substracting the embedding for “she” and “he”, or “woman” and “man”, or as showed in the section on chapter 4, by adding those differences. In the Canadian case, then how and where do words studied in chapters 4 and 5 appear within the conservative, liberal or progressive subspace. For instance, where is “bourgeois” in conservative subspace; in the liberal subspace. Where is “bureaucracy”?

<!-- One other item is of interest to me. The way it can be operationalized and tested is yet to be defined, but it concerns the way “others” or “opponents” are characterized in speech. In van Dijk’s (2006) terms: 

> "When ideologies are mapped onto discourse, they typically become expressed in terms of their own underlying structures, such as the polarization between positive ingroup description and negative outgroup description. This may take place not only explicitly by propositional means (topics, meanings, etc.), but also by many other discursive moves that emphasize or de-emphasize Our/Their Good/Bad Things, such as headlines and position, sound structures and visuals, lexicalization, syntactic structure, semantic moves such as disclaimers, and a host of rhetorical figures and argumentation moves."

It is not fully clear to me yet how this outgroup otherness and ingroup sameness can be scrutinized using word embeddings, but it probably involves training a model that predicts the type of outgroup that is mentioned in tweets. The question would then be: inside the conservative/liberal subspaces, can we predict type of ingroup/outgroup mentioned (those cosmopolitans; those immigrants; those rednecks; us real Canadians; us real progressives, etc.)?

-->