# Case justification and contribution

Why Canada? The use of word embeddings to study meaning is recent (the idea is old, but efficient implementation is recent (2013)). Work in applied political science is very recent (less than five years old). As it is often the case in such a situation, almost all applied work focuses on the American case [@rodman2020timely,@kozlowski2019geometry]. While these studies find interesting results for the study of culture and meaning, these results need to be tested outside the American case. Rodman, for instance, finds semantic change around the term “equality” that is specific to the United States. Other countries certainly saw the term evolve in a slightly different way. Furthermore, most of the work studying meaning with embeddings is in the English language. Canada is an interesting case as conversations about politics usually take place in English and French. While this dissertation will not explicitly rely on the analysis of French text, this certainly is the next step in the Canadian context. Hence, studying the Canadian case opens the door to a bilingual analysis, something more difficult in the United States or in Europe (with evident caveats in Europe like Belgium). 

Next, as discussed in the third section of the literature review, the Canadian case is interesting due to the nature of it’s shifting, ambivalent, political identity. Major cases studied (e.g. Britain, United States) are countries with a history of (more) explicit self-understanding. Thinking of the United States, people usually think of a mature world leader, of “Life, Liberty and the pursuit of Happiness”, of the American nation, of the "extremes". The political science literature is more ambiguous as regards to what constitutes Canadian identity. Does this ambivalence still allow to capture meaningful associations using word embeddings?  

Finally, the main contribution of this dissertation is to apply word embeddings models to the study of Canadian politics. Word embeddings models offer a new and highly attractive way to study meaning. While it has been used by some social researchers in the last five years, my belief is that the full power of the method has not been utilized yet, and it’s thorough application, especially focusing on diachronic embeddings, has the potential to shed new light on our understanding of how people talk about politics. Natural Language Processing (NLP) methods are perhaps the next (already started) technological revolution [@floridi2020gpt;@lakhotia2021generative]. This dissertation is a humble contribution to the adavancement of their understanding in applied social science.  
